#+TITLE: Magik - A simple python utility to open links
#+AUTHOR: pace577

Magik lets you quickly open links using a simple command. You can also run it with a timetable, and it will open links by itself. This is primarily for all those students who struggle to open and manage links to lectures/course material on a regular basis, however anyone's free to modify and use it!

* Dependencies
All you need is a working python (tested on Python version 3.9) setup! And maybe an office utility like [[https://www.libreoffice.org/discover/calc/][Libreoffice Calc]] to edit csv files while keeping hold of your sanity.


* How it works
Magik reads a CSV file that contains links corresponding to the subject name, and opens the link with a given browser. The ~vars.py~ file contains information about the column headings and rows, which can be customized according to your needs.


* How to use it
** Creating and editing the CSV file
First change the /Customization variables/ provided in ~vars.py~ according to your needs. Change the =BROWSER= variable to "chrome" if you are using the Google Chrome browser.

Other important variables are =SUBJECT_LIST= and =SUBJECT_ARGS_LIST= for magik to work. If using watch mode (which is probably why you would want to use Magik), set the =TIME_LIST= and =DAY_LIST= variables to set your timetable accordingly.

Then the following command will create CSV files with names given by =LINK_FILE= and =TIME_FILE= in ~vars.py~, according to your /Customization Variables/ set in the same file.
#+begin_src bash
./magik.py init
#+end_src

- =LINK_FILE= contains all your links, arranged in a table. Each row corresponds to a subject (math, science, etc) and each column corresponds to a link type (link to attend live lectures, link to view recorded lectures, etc)
- =TIME_FILE= contains the timetable. Each row corresponds to a day, and columns correspond to a time (in HH:MM format). You must put subject names (as given in the first column of =LINK_FILE=) in the appropriate time slots. Magik will open the link for that subject, that are in the second column of =LINK_FILE=. To know more, read [[Watch mode]]

You can edit and add links to =LINK_FILE= and subject names to =TIME_FILE= using an office tool like Libreoffice Calc or MS Excel.

Alternatively, you can use the ~set~ command to add links to =LINK_FILE=. For example, if you want to set the link to subject ~math~ and link type ~lecture~ as https://youtube.com, then use the following command.
#+begin_src bash
./magik.py set math lecture https://youtube.com
#+end_src


** Watch mode
Magik can read a timetable and open links by itself at a set time. The links opened correspond to the second column of the specified subject, as given in =LINK_FILE=. If you know at what times in the future you have to open a link, Magik can open it without you having to explicitly run it every time you need to open a link.

You can set your timetable in the ~times.csv~ file. An example is as follows
#+begin_src csv
Day,09:00,10:00,11:00,12:00
Mon,cv,math,ps-2,cv
Tue,math,cv,ps-1,ps-1
Wed,math,cv,ps-2,cv
Thu,cv,math,ps-1,cv
Fri,cv,math,math,cv
#+end_src
The subject names must be the same as in the first column of ~links.csv~.

As previously mentioned, Magik supports multiple links. Put space separated links in the second column of =LINK_FILE= and mention the link you want to open in =<subject>-<link_number>= format in =TIME_FILE=.

Start watch mode with the following. Kill the program to exit it.
#+begin_src bash
./magik.py watch
#+end_src

Consider creating a Systemd service for Magik for autostarting it every time you boot your device.


** Opening links
When the CSV file is ready, you can use ~magik~ to open a link immediately. Consider the ~links.csv~ file for example. It has the following contents:
#+begin_src csv
subject,live_lectures,recorded_lectures,assignments
ps,https:archlinux.org https://duckduckgo.com,https:archlinux.org,https:archlinux.org
cv,https:archlinux.org,https:archlinux.org,https:archlinux.org
math,https:archlinux.org,https:archlinux.org,https:archlinux.org
#+end_src

To open the link corresponding to ~ps~ and ~live_lectures~, use the following command while in the project directory:
#+begin_src bash
./magik.py open cv live_lectures
#+end_src

You can use short commands to do the same thing, which can be customized in the ~vars.py~ file.
#+begin_src bash
./magik.py o cv live
#+end_src
The default value for the last argument is ~live_lectures~ (in particular, it is the heading of the leftmost column containing links), so it can be skipped if desired.

Note that the ~live_lectures~ column in ~ps~ row has 2 space separated links. You can open the desired link by specifying the link number using a '-'. For example, if you want to open the 1st link for ~ps~:
#+begin_src csv
./magik.py o ps-1 live
#+end_src



* Customizing
You can customize a lot of variables in the ~vars.py~ file to suit your needs.

| Variable Name       | Description                                                                                                                            |
|---------------------+----------------------------------------------------------------------------------------------------------------------------------------|
| BROWSER             | The browser used to open links. Make sure this is the *same* as the browsers commandline utility                                        |
| LINK_FILE           | The CSV file that contains all the links read by the program.                                                                          |
| TIME_FILE           | The CSV file that contains the times read by the program. These times correspond to a subject in LINK_FILE.                            |
| SUBJECT             | The CSV file heading for the subject column in =LINK_FILE=. Used to create the =LINK_FILE= file with ~magik init~                              |
| DAY                 | The CSV file heading for the subject column in =TIME_FILE=. Used to create the =TIME_FILE= file with ~magik init~.                             |
| SUBJECT_LIST        | List of subjects(rows) under the 'subject' column. Must be the same as in the CSV file.                                                |
| SUBJECT_ARGS_LIST   | List of lists containing arguments that map to an item in =SUBJECT_LIST=. Customize this to use short arguments when running commands.     |
| LINK_TYPE_LIST      | List of link types (column headings) in the CSV file. Must be the same as in the CSV file. Used in =LINK_FILE=.                           |
| LINK_TYPE_ARGS_LIST | List of lists containing arguments that map to an item in =LINK_TYPE_LIST=. Customize this to use short arguments when running commands.  |
| TIME_LIST           | For watch mode. List of time slots for the timetable (column headings) in =TIME_FILE=                                                     |
| DAY_LIST            | For watch mode. List of days for the timetable (row headings) in =TIME_FILE=                                                              |
| EARLY               | For watch mode. Magik will open the link =EARLY= seconds before the next event time, as given in =TIME_FILE=                                 |

Also, consider placing a symlink for magik.py somewhere in your PATH, so you can execute it from anywhere.
